=== cambridge-collection/cudl-package-schemas/JSON-package-format/schemas/collection.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://schemas.cudl.lib.cam.ac.uk/package/v1/collection.json",

  "definitions": {
  },

  "type": "object",
  "properties": {
    "@type": {"const":  "https://schemas.cudl.lib.cam.ac.uk/package/v1/collection.json"},

    "name": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "url-slug": {"type": "string"},
            "sort": {"type": "string"},
            "short": {"type": "string"},
            "full": {"type": "string"}
          },
          "additionalProperties": false
        },
        {
          "$comment": "short or full (or both) must always be present",
          "anyOf": [
            {"type":  "object", "required": ["short"]},
            {"type":  "object", "required": ["full"]}
          ]
        }
      ]
    },

    "description": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "short": {"type": "string"},
            "medium": {"type": "string"},
            "full": {"$ref": "common.json#/definitions/htmlReference"}
          },
          "additionalProperties": false,
          "minProperties": 0
        }
      ]
    },

    "credit": {
      "type": "object",
      "properties": {
        "parties": {
          "type": "array",
          "items": {
            "oneOf": [
              {"$ref": "common.json#/definitions/moduleReference"},
              {
                "$comment": "Use properties from https://schema.org/ Organisation or Person",
                "type": "object",
                "properties": {
                  "@type": {"enum":  ["Organisation", "Person"]},
                  "name": {"type":  "string"},
                  "url": {"type":  "string", "format": "uri"}
                },
                "required": ["@type", "name"]
              }
            ]
          }
        },
        "prose": {"$ref": "common.json#/definitions/htmlReference"}
      },
      "required": []
    },

    "items": {
      "type": "array",
      "items": {
        "oneOf": [
          {"$ref": "common.json#/definitions/moduleReference"},
          {
            "type": "object",
            "properties": {
              "item": {"$ref": "common.json#/definitions/moduleReference"},
              "visible": {"type": "boolean"}
            },
            "required": ["item"]
          }
        ]
      }
    },

    "collections": {
      "type": "array",
      "items": {"$ref": "common.json#/definitions/moduleReference"}
    }

  },
  "required": ["@type", "name"],
  "additionalProperties": false
}

=== cambridge-collection/cudl-package-schemas/JSON-package-format/examples/MUDL/complete-example/mysite/collection1/collection1.json
{
  "@type": "https://schemas.cudl.lib.cam.ac.uk/package/v1/collection.json",

  "name": {
    "url-slug": "collection1",
    "sort": "First Collection, The",
    "short": "The First Collection",
    "full": "This is the very first collection"
  },

  "description": {
    "short": "This collection contains some items that are very important.",
    "medium": "This collection contains some items that are very important.  They are very interesting for lots of reasons.",

    "full": { "@id": "./description/summary.html" }
  },

  "items": [
    { "item": { "@id": "./item1/item1.tei.xml" },
      "visible": false },
    { "@id": "./item1/item1.json" }
  ]

}

=== cambridge-collection/cudl-package-schemas/JSON-package-format/tests/collection/valid/kitchen-sink.json
{
  "@type": "https://schemas.cudl.lib.cam.ac.uk/package/v1/collection.json",

  "name": {
    "url-slug": "hebrew",
    "sort": "0. Hebrew Manuscripts",
    "short": "Hebrew Manuscripts",
    "full": "The Hebrew Manuscripts of Cambridge University Library"
  },

  "description": {
    "short": "Manuscripts and printed books from Cambridge University Library's Hebrew collections",
    "medium": "For over five hundred years Cambridge University has been building up one of the worldâ€™s most important collections of Hebrew manuscripts.",
    "full": {"@id":  "hebrew-description.html"}
  },

  "credit": {
    "parties": [
      {
        "@type": "Organisation",
        "name": "Example Organisation 2",
        "url":  "http://exampleorganisation2.example.com/",
        "knowsAbout": "Potatoes"
      },
      {
        "@type": "Person",
        "name": "Example Person 1",
        "url":  "http://exampleperson1.example.com/",
        "knowsAbout": "Onions"
      },
      {"@id": "referenced-modules/funder-organisation.json"},
      {"@id": "referenced-modules/funder-person.json"}
    ],
    "prose": {"@id": "hebrew-funders.html"}
  },

  "items": [
    {"@id": "item.json"}
  ],

  "collections": [
    {"@id": "minimal.json"}
  ]
}
