=== cambridge-collection/cudl-package-schemas/simple/collection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  targetNamespace="http://cudl.lib.cam.ac.uk/1.0/collection" 
  xmlns:collection="http://cudl.lib.cam.ac.uk/1.0/collection">
  <xs:element name="collection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="collection:title"/>
        <xs:element ref="collection:collType"/>
        <xs:element ref="collection:parentCollectionId" minOccurs="0"/>
        <xs:element ref="collection:metaDescription"/>
        <xs:element ref="collection:resources"/>
        <xs:element ref="collection:items"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="collType" type="xs:NCName"/>
  <xs:element name="parentCollectionId" type="xs:NCName"/>
  <xs:element name="metaDescription" type="xs:string"/>
  <xs:element name="resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="collection:resource"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="resource">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="collection:type"/>
        <xs:element ref="collection:representation"/>
        <xs:element ref="collection:target"/>
        <xs:element ref="collection:location"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="type">
    <xs:simpleType>
      <xs:restriction base="xs:NCName">
        <xs:enumeration value="webcontent"/>
        <xs:enumeration value="image"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element> 
  <xs:element name="representation">
    <xs:simpleType>
      <xs:restriction base="xs:NCName">
        <xs:enumeration value="html"/>
        <xs:enumeration value="tif"/>
        <xs:enumeration value="jpg"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element> 
  <xs:element name="target" type="xs:NCName"/>
  <xs:element name="location">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="(https?:/)?(/([_0-9a-zA-Z\.\-])+)+"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element> 
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="collection:item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cambridge-collection/cudl-package-schemas/XML-package-format/examples/MUDL/collection-petrarch.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection id="petrarch" xmlns="http://cudl.lib.cam.ac.uk/1.0/collection" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/collection collection.xsd">
   <title>Petrarch Printed Editions</title>
   <type>organisation</type>
   <metaDescription>A collection of Manuscripts provided by Manchester University</metaDescription>
   <resources>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>summary</target>
         <location>collections/petrarch/summary.html</location>
      </resource>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>sponsors</target>
         <location>collections/petrarch/sponsors.html</location>
      </resource>
   </resources>
   <items>
      <item id="MS-PETRARCH-INC-18313"/>
      <item id="MS-PETRARCH-MSS-20957"/>
      <item id="MS-PETRARCH-MSS-01546"/>
   </items>
</collection>

=== cambridge-collection/cudl-package-schemas/XML-package-format/examples/MUDL/collection-latin.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection id="latin" xmlns="http://cudl.lib.cam.ac.uk/1.0/collection" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/collection collection.xsd">
   <title>Latin Manuscripts</title>
   <type>organisation</type>
   <metaDescription>A collection of Latin Manuscripts provided by Manchester University</metaDescription>
   <resources>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>summary</target>
         <location>collections/latin/summary.html</location>
      </resource>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>sponsors</target>
         <location>collections/latin/sponsors.html</location>
      </resource>
   </resources>
   <items>
      <item id="MS-LATIN-00008"/>
   </items>
</collection>

=== cambridge-collection/cudl-package-schemas/XML-package-format/examples/CUDL/collection-landscapehistories.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection id="landscapehistories"  xmlns="http://cudl.lib.cam.ac.uk/1.0/collection" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/collection collection.xsd">
   <title>Landscape histories from the air: unlocking a UK-wide archive</title>
   <type>organisation</type>
   <metaDescription>A collection of photos.</metaDescription>
   <resources>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>summary</target>
         <location>collections/landscapehistories/summary.html</location>
      </resource>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>sponsors</target>
         <location>collections/landscapehistories/sponsors.html</location>
      </resource>
   </resources>
   <items>
      <item id="PH-GEOGRAPHY-35KAB-00034"/>
      <item id="PH-GEOGRAPHY-70HC-00022"/>
   </items>
</collection>

=== cambridge-collection/cudl-package-schemas/XML-package-format/examples/CUDL/collection-longitude.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection id="longitude"  xmlns="http://cudl.lib.cam.ac.uk/1.0/collection" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/collection collection.xsd">
   <title>Board of Longitude</title>
   <type>organisation</type>
   <metaDescription>A collection of Manuscripts from the Board of Longitude.</metaDescription>
   <resources>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>summary</target>
         <location>collections/longitude/summary.html</location>
      </resource>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>sponsors</target>
         <location>collections/longitude/sponsors.html</location>
      </resource>
   </resources>
   <items>
      <item id="MS-RGO-00005-00229"/>
   </items>
</collection>

=== cambridge-collection/cudl-package-schemas/examples/XML Input/CUDL/collection-darwin_mss.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection id="darwin_mss" xmlns="http://cudl.lib.cam.ac.uk/1.0/collection" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/collection collection.xsd">
   <title>Darwin Manuscripts</title>
   <type>organisation</type>
   <metaDescription>A collection of Manuscripts Charles Darwin.</metaDescription>
   <resources>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>summary</target>
         <location>collections/darwin_mss/summary.html</location>
      </resource>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>sponsors</target>
         <location>collections/darwin_mss/sponsors.html</location>
      </resource>
   </resources>
   <items>
      <item id="MS-DAR-00100-00001"/>
      <item id="MS-DAR-00114-00001"/>
   </items>
</collection>

=== cambridge-collection/cudl-package-schemas/XML-package-format/examples/CUDL/collection-newton.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection id="newton"  xmlns="http://cudl.lib.cam.ac.uk/1.0/collection" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/collection collection.xsd">
   <title>Newton Manuscripts</title>
   <type>organisation</type>
   <metaDescription>A collection of Manuscripts Isaac Newton.</metaDescription>
   <resources>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>summary</target>
         <location>collections/newton/summary.html</location>
      </resource>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>sponsors</target>
         <location>collections/newton/sponsors.html</location>
      </resource>
   </resources>
   <items>
      <item id="MS-ADD-03960"/>
      <item id="MS-ADD-03975"/>
   </items>
</collection>

=== cambridge-collection/cudl-package-schemas/XML-package-format/examples/MUDL/collection-hebrew.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection id="hebrew" xmlns="http://cudl.lib.cam.ac.uk/1.0/collection" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/collection collection.xsd">
   <title>Hebrew Manuscripts</title>
   <type>organisation</type>
   <metaDescription>A collection of Hebrew Manuscripts provided by Manchester University</metaDescription>
   <resources>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>summary</target>
         <location>collections/hebrew/summary.html</location>
      </resource>
      <resource>
         <type>webcontent</type>
         <representation>html</representation>
         <target>sponsors</target>
         <location>collections/hebrew/sponsors.html</location>
      </resource>
   </resources>
   <items>
      <item id="MS-HEBREW-GASTER-00086"/>
      <item id="MS-HEBREW-GASTER-00274"/>
      <item id="MS-HEBREW-MSS-00008"/>
   </items>
</collection>
