=== cambridge-collection/cudl-package-schemas/simple/item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  targetNamespace="http://cudl.lib.cam.ac.uk/1.0/item" 
  xmlns:item="http://cudl.lib.cam.ac.uk/1.0/item">
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item:flags"/>
        <xs:element ref="item:resources"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="flags">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item:iiifenabled"/>
        <xs:element ref="item:taggingstatus" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="iiifenabled" type="xs:boolean"/>
  <xs:element name="taggingstatus" type="xs:boolean" default="false"/>
  <xs:element name="resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="item:resource"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="resource">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item:type"/>
        <xs:element ref="item:representation"/>
        <xs:element ref="item:location"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="type" type="xs:NCName"/>
  <xs:element name="representation" type="xs:NCName"/>
  <xs:element name="location" type="xs:string"/>
</xs:schema>

=== cambridge-collection/cudl-package-schemas/examples/CUDL/PH-GEOGRAPHY-70HC-00022/PH-GEOGRAPHY-70HC-00022.xml
<?xml version="1.0" encoding="UTF-8"?>
<item id="PH-GEOGRAPHY-70HC-00022" xmlns="http://cudl.lib.cam.ac.uk/1.0/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/item item.xsd">
   <flags/>
   <resources>
      <resource>
         <type>metadata</type>
         <representation>tei</representation>
         <location>/v1/metadata/tei/PH-GEOGRAPHY-70HC-00022/</location>
      </resource>
      <resource>
         <type>image</type>
         <representation>jp2</representation>
         <location>PH-GEOGRAPHY-70HC-00022-000-00001.jp2</location>
      </resource>
   </resources>
</item>

=== cambridge-collection/cudl-package-schemas/XML-package-format/examples/CUDL/MS-DAR-00114-00001/MS-DAR-00114-00001.xml
<?xml version="1.0" encoding="UTF-8"?>
<item id="MS-DAR-00114-00001" xmlns="http://cudl.lib.cam.ac.uk/1.0/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/item item.xsd">
   <flags/>
   <resources>
      <resource>
         <type>metadata</type>
         <representation>dcp</representation>
         <location>/v1/metadata/dcp/MS-DAR-00114-00001/</location>
      </resource>
      <resource>
         <type>image</type>
         <representation>jp2</representation>
         <location>MS-DAR-00114-00001-000-00001.jp2</location>
      </resource>
      <resource>
         <type>image</type>
         <representation>jp2</representation>
         <location>MS-DAR-00114-00001-000-00002.jp2</location>
      </resource>
      <resource>
         <type>image</type>
         <representation>jp2</representation>
         <location>MS-DAR-00114-00001-000-00003.jp2</location>
      </resource>
      <resource>
         <type>image</type>
         <representation>jp2</representation>
         <location>MS-DAR-00114-00001-000-00004.jp2</location>
      </resource>
      <resource>
         <type>image</type>
         <representation>jp2</representation>
         <location>MS-DAR-00114-00001-000-00005.jp2</location>
      </resource>
      <resource>
         <type>image</type>
         <representation>jp2</representation>
         <location>MS-DAR-00114-00001-000-00006.jp2</location>
      </resource>
      <resource>
         <type>image</type>
         <representation>jp2</representation>
         <location>MS-DAR-00114-00001-000-00007.jp2</location>
      </resource>
      <resource>
         <type>image</type>
         <representation>jp2</representation>
         <location>MS-DAR-00114-00001-000-00008.jp2</location>
      </resource>
   </resources>
</item>
