=== cambridge-collection/cudl-package-schemas/simple/site.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  targetNamespace="http://cudl.lib.cam.ac.uk/1.0/site" 
  xmlns:site="http://cudl.lib.cam.ac.uk/1.0/site">
  <xs:element name="site">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="site:collections"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="collections">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="site:collection"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="collection">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cambridge-collection/cudl-package-schemas/semantic/site.xml
<?xml version="1.0" encoding="UTF-8"?>
<site xmlns="http://cudl.lib.cam.ac.uk/1.0/site"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://cudl.lib.cam.ac.uk/1.0/site site.xsd"
    
    id="johnrylands">
    
    <collections>
        <collection id="hebrew"/>      
        <collection id="petrarch"/>
        <collection id="landscapehistories"/>
        <collection id="treasures"/>
        <collection id="sassoon"/>
        <collection id="lewisgibson"/>
        <collection id="darwinhooker"/>
        <collection id="japanese"/>
        <collection id="tennyson"/>
    </collections>
    
</site>
