=== cambridge-collection/cudl-package-schemas/item.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {

    "orientation": {
      "type": "string",
      "enum": ["portrait", "landscape"]
    },

    "html": {
      "type": "string",
      "contentMediaType": "text/html"
    },

    "descriptiveMetadataSection": {
      "type": "object",
      "allOf": [
        { "$ref": "#/definitions/topLevelDescriptiveMetadataProperties" },
        { "$ref": "#/definitions/metadataContainer" }
      ]
    },

    "topLevelDescriptiveMetadataProperties": {
      "type": "object",
      "properties": {
        "ID": { "type": "string" },

        "thumbnailUrl": { "type": "string", "format": "uri-reference" },
        "thumbnailOrientation": { "$ref": "#/definitions/orientation" },
        "displayImageRights": { "$ref": "#/definitions/html" },
        "downloadImageRights": { "$ref": "#/definitions/html" },
        "imageReproPageURL": { "type": "string", "format": "uri-reference" },
        "docAuthority": { "$ref": "#/definitions/html" },
        "type": { "type": "string", "enum": ["text"] },
        "manuscript": { "type": "boolean" },
        "itemReferences": {
          "$comment": "Used in itemType: essay to link to related items",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "ID": {
                "$comment": "IDs are item JSON filenames without the .json extension",
                "type": "string"
              }
            }
          }
        }
      }
    },

    "metadataContainer": {
      "title": "Metadata Container",
      "description": "An object directly containing displayable descriptive metadata objects, or objects with value arrays containing nested Metadata Containers.",
      "type": "object",
      "additionalProperties": {
        "anyOf": [
          {
            "title": "Nested metadata ",
            "type": "object",
            "not": {
              "$comment": "Dont' allow label property",
              "type": "object",
              "required": ["label"]
            },
            "properties": {
              "value": {
                "type": "array",
                "items": { "$ref": "#/definitions/metadataContainer" }
              }
            }
          },
          { "$ref": "#/definitions/metadataItem" },
          {
            "type": "string",
            "format": "uri-reference"
          },
          {
            "$comment": "Allow any other objects, arrays or booleans (e.g. manuscript = True). As a result none of the above *has* to match, it basically serves to document the objects which are used.",
            "type": ["object", "array", "boolean"]
          }
        ]
      }
    },

    "metadataItem": {
      "type": "object",
      "properties": {
        "display": { "const": true },
        "seq": { "type": "integer" },
        "label": { "type": "string" }
      },
      "required": ["display", "seq", "label"],

      "oneOf": [
        {
          "$comment": "Text items",
          "type": "object",
          "properties": {
            "displayForm": { "type": "string", "contentMediaType": "text/html" }
          },
          "required": ["displayForm"]
        },
        {
          "$comment": "Multi-valued items",
          "type": "object",
          "properties": {
            "value": {
              "type": "array",
              "items": { "$ref": "#/definitions/metadataItem" }
            }
          },
          "required": ["value"]
        },
        {
          "$comment": "String items",
          "type": "string",
          "properties": {
            "displayForm": { "type": "string", "contentMediaType": "text/html" }
          },
          "required": ["value"]
        }
      ]
    },

    "page": {
      "type": "object",
      "properties": {
        "label": { "type": "string" },
        "physID": { "type": "string" },
        "sequence": { "type": "integer" },
        "displayImageURL": { "type": "string", "format": "uri-reference" },
        "downloadImageURL": { "type": "string", "format": "uri-reference" },
        "IIIFImageURL": { "type": "string", "format": "uri-reference" },
        "thumbnailImageURL": { "type": "string", "format": "uri-reference" },
        "thumbnailImageOrientation": { "$ref": "#/definitions/orientation" },
        "imageWidth": { "type": "integer" },
        "imageHeight": { "type": "integer" },
        "transcriptionNormalisedURL": { "type": "string", "format": "uri-reference" },
        "transcriptionDiplomaticURL": { "type": "string", "format": "uri-reference" },
        "content": {
          "$comment": "Used in itemType: essay to hold the text of the essay consituting the item.",
          "type": "string",
          "contentMediaType": "text/html"
        },
        "pageType": { "type": "string" }
      }
    },

    "listItemPage": {
      "type": "object",
      "properties": {
        "fileID": { "type": "string" },
        "dmdID": { "type": "string" },
        "startPageLabel": { "type": "string" },
        "startPage": { "type": "integer" },
        "title": { "type": "string" },
        "listItemText": { "type": "string" }
      },
      "additionalProperties": false
    },

    "logicalStructureNode": {
      "type": "object",
      "properties": {
        "descriptiveMetadataID": { "type": "string" },
        "label": { "type": "string" },
        "startPageID": { "type": "string" },
        "startPageLabel": { "type": "string" },
        "startPagePosition": { "type": "integer" },
        "endPageID": { "type": "string" },
        "endPageLabel": { "type": "string" },
        "endPagePosition": { "type": "integer" },
        "children": {
          "type": "array",
          "items": { "$ref": "#/definitions/logicalStructureNode" }
        }
      },
      "required": ["descriptiveMetadataID", "label", "startPagePosition",
        "startPageLabel", "endPagePosition"]
    }
  },

  "type": "object",

  "properties": {
    "descriptiveMetadata": {
      "type": "array",
      "items": { "$ref": "#/definitions/descriptiveMetadataSection" }
    },
    "pages": {
      "type": "array",
      "items": { "$ref": "#/definitions/page" }
    },
    "logicalStructures": {
      "type": "array",
      "items": { "$ref": "#/definitions/logicalStructureNode" }
    },
    "listItemPages": {
      "type": "array",
      "items": { "$ref": "#/definitions/listItemPage" }
    },
    "textDirection": {
      "type": "string",
      "enum": ["L", "R"]
    },
    "itemType": { "type": "string", "enum": ["essay"] },
    "numberOfPages": { "type": "integer" },
    "embeddable": { "type": "boolean" },
    "sourceData": { "type": "string", "format": "uri-reference" },
    "useTranscriptions": { "type": "boolean" },
    "useNormalisedTranscriptions": { "type": "boolean" },
    "useDiplomaticTranscriptions": { "type": "boolean" },
    "allTranscriptionDiplomaticURL": { "type": "string", "format": "uri-reference" },
    "completeness": { "type": "string" }
  },

  "required": ["descriptiveMetadata", "pages", "logicalStructures"],
  "additionalProperties": false
}

=== cambridge-collection/cudl-package-schemas/examples/CUDL/PH-GEOGRAPHY-35KAB-00034/PH-GEOGRAPHY-35KAB-00034.json
{
 "logicalStructures": [{
  "endPagePosition": 1,
  "startPageLabel": "1",
  "startPageID": "PHYS-1",
  "descriptiveMetadataID": "ITEM-1",
  "label": "Hospital. Cambridge, Addenbrookes , Cambs, UK",
  "startPagePosition": 1,
  "endPageLabel": "1"
 }],
 "pages": [{
  "displayImageURL": "/content/images/PH-GEOGRAPHY-35KAB-00034-000-00001.dzi",
  "imageWidth": 7235,
  "sequence": 1,
  "thumbnailImageURL": "/content/images/PH-GEOGRAPHY-35KAB-00034-000-00001_files/8/0_0.jpg",
  "IIIFImageURL": "PH-GEOGRAPHY-35KAB-00034-000-00001.jp2",
  "downloadImageURL": "/content/images/PH-GEOGRAPHY-35KAB-00034-000-00001.jpg",
  "label": "1",
  "physID": "PHYS-1",
  "thumbnailImageOrientation": "landscape",
  "imageHeight": 4701
 }],
 "numberOfPages": 1,
 "descriptiveMetadata": [{
  "extent": {
   "display": true,
   "label": "Extent",
   "displayForm": "1 photograph",
   "seq": 171
  },
  "physicalLocation": {
   "display": true,
   "label": "Physical Location",
   "displayForm": "Cambridge University Collection of Aerial Photography",
   "seq": 4
  },
  "notes": {
   "display": true,
   "label": "Note(s)",
   "value": [{
    "display": true,
    "displayForm": "For full record see <a target='_blank' class='externalLink' href='https://www.cambridgeairphotos.com/location/35kab034/'>https://www.cambridgeairphotos.com/location/35kab034/<\/a>",
    "seq": 163
   }],
   "seq": 162
  },
  "thumbnailOrientation": "landscape",
  "shelfLocator": {
   "display": true,
   "label": "Classmark",
   "displayForm": "35kAB034",
   "seq": 5
  },
  "subjects": {
   "display": true,
   "listDisplay": "inline",
   "label": "Subject(s)",
   "value": [{
    "display": true,
    "linktype": "keyword search",
    "fullForm": "Aerial photography",
    "displayForm": "Aerial photography",
    "seq": 21
   }],
   "seq": 20
  },
  "displayImageRights": "Zooming image copyright Cambridge University Collection of Aerial Photography",
  "metadataRights": "This metadata is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.",
  "imageReproPageURL": "https://www.cambridgeairphotos.com/",
  "title": {
   "display": false,
   "label": "Title",
   "displayForm": "Hospital. Cambridge, Addenbrookes , Cambs, UK",
   "seq": 8
  },
  "fundings": {
   "display": true,
   "label": "Funding",
   "value": [{
    "display": true,
    "displayForm": "",
    "seq": 201
   }],
   "seq": 200
  },
  "docAuthority": "",
  "creations": {
   "display": true,
   "value": [{
    "places": {
     "display": true,
     "label": "Origin Place",
     "value": [{
      "display": true,
      "linktype": "keyword search",
      "shortForm": "52.175613 0.141032",
      "displayForm": "52.175613 0.141032",
      "seq": 69
     }],
     "seq": 68
    },
    "dateDisplay": {
     "display": true,
     "linktype": "keyword search",
     "label": "Date of Creation",
     "displayForm": "21/10/1970",
     "seq": 77
    },
    "dateStart": "1970",
    "dateEnd": "1970",
    "type": "creation"
   }],
   "seq": 63
  },
  "ID": "ITEM-1",
  "downloadImageRights": "Images made available for download are licensed under a Creative Commons Attribution-NonCommercial 3.0 Unported License (CC BY-NC 3.0)",
  "thumbnailUrl": "/content/images/PH-GEOGRAPHY-35KAB-00034-000-00001_files/8/0_0.jpg"
 }],
 "sourceData": "/v1/metadata/tei/PH-GEOGRAPHY-35KAB-00034/",
 "embeddable": true
}

=== cambridge-collection/cudl-package-schemas/Internal-JSON-format/tests/item/valid/PH-GEOGRAPHY-KE-00001.json
{
  "descriptiveMetadata": [
    {
      "subjects": {
        "display": true,
        "seq": 20,
        "listDisplay": "inline",
        "label": "Subject(s)",
        "value": [
          {
            "display": true,
            "displayForm": "Aerial photography",
            "seq": 21,
            "linktype": "keyword search",
            "fullForm": "Aerial photography"
          }
        ]
      },
      "creations": {
        "display": true,
        "seq": 63,
        "value": [
          {
            "type": "creation",
            "dateStart": "1948",
            "dateEnd": "1948",
            "dateDisplay": {
              "display": true,
              "displayForm": "1948-07-24",
              "linktype": "keyword search",
              "label": "Date of Creation",
              "seq": 77
            }
          }
        ]
      },
      "physicalLocation": {
        "display": true,
        "displayForm": "Cambridge University Collection of Aerial Photography",
        "label": "Physical Location",
        "seq": 4
      },
      "shelfLocator": {
        "display": true,
        "displayForm": "K-E1",
        "label": "Classmark",
        "seq": 5
      },
      "thumbnailUrl": "/content/images/PH-GEOGRAPHY-KE-00001-000-00001_files/8/0_0.jpg",
      "thumbnailOrientation": "landscape",
      "displayImageRights": "Zooming image copyright Cambridge University Collection of Aerial Photography",
      "downloadImageRights": "Images made available for download are licensed under a Creative Commons Attribution-NonCommercial 3.0 Unported License (CC BY-NC 3.0)",
      "imageReproPageURL": "https://www.cambridgeairphotos.com/",
      "metadataRights": "This metadata is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.",
      "docAuthority": "",
      "fundings": {
        "display": true,
        "seq": 200,
        "label": "Funding",
        "value": [
          {
            "display": true,
            "displayForm": "",
            "seq": 201
          }
        ]
      },
      "extent": {
        "display": true,
        "displayForm": "1 photograph",
        "label": "Extent",
        "seq": 171
      },
      "ID": "ITEM-1",
      "title": {
        "display": false,
        "displayForm": "Silchester, Hants",
        "label": "Title",
        "seq": 8
      }
    }
  ],
  "numberOfPages": 1,
  "embeddable": true,
  "sourceData": "/v1/metadata/tei/PH-GEOGRAPHY-KE-00001/",
  "pages": [
    {
      "label": "1",
      "physID": "PHYS-1",
      "sequence": 1,
      "displayImageURL": "/content/images/PH-GEOGRAPHY-KE-00001-000-00001.dzi",
      "downloadImageURL": "/content/images/PH-GEOGRAPHY-KE-00001-000-00001.jpg",
      "IIIFImageURL": "PH-GEOGRAPHY-KE-00001-000-00001.jp2",
      "thumbnailImageURL": "/content/images/PH-GEOGRAPHY-KE-00001-000-00001_files/8/0_0.jpg",
      "thumbnailImageOrientation": "landscape",
      "imageWidth": 6906,
      "imageHeight": 6627
    }
  ],
  "logicalStructures": [
    {
      "descriptiveMetadataID": "ITEM-1",
      "label": "Silchester, Hants",
      "startPageLabel": "1",
      "startPagePosition": 1,
      "startPageID": "PHYS-1",
      "endPageLabel": "1",
      "endPagePosition": 1
    }
  ]
}
